version: '3'
services:
  apache:
    build: .docker/apache
    container_name: stripe_apache
    ports:
      - "88:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    #image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: stripe_mysql
    expose:
      - '3306'
    ports:
      - "3307:3306"
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stripe_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build: .docker/php
    container_name: stripe_php
    volumes:
      - .:/home/wwwroot
    environment:
      - maildev_host=stripe_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stripe_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: stripe_maildev
    ports:
      - "8001:80"
